name: Build and publish bottles

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Prepare
        run: brew upgrade && brew tap ncihnegn/homebrew-formulae
      - name: Build
        run: brew install --build-bottle toml11 && brew bottle toml11
      - name: Upload
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.bottle.tar.gz'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
