name: Build and publish bottles

on:
  create:
    tags:
      - '*-*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: brew tap ncihnegn/homebrew-formulae
      - name: Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{github.ref}}
          draft: false
          prerelease: false
      - name: Build
        id: build
        run: |
          tag=$(echo ${{github.ref}} | cut -c11-)
          package=$(echo $tag | cut -d'-' -f1)
          brew install --build-bottle ${package}
          bottle=$(brew bottle ${package} --root-url https://github.com/${{github.repository}}/releases/download/${tag})
          echo ${bottle}
          file_name=$(echo ${bottle} | sed 's/.* \([0-9a-z.-]*.tar.gz\).*/\1/')
          echo ${file_name}
          dsl=$(echo ${bottle} | sed 's/.*do \(.*\)end/\1/')
          echo ${dsl}
          sed -i.bak "s/root_url.*/${dsl:q}/" ${package}.rb
          git config --global user.name "GitHub Action"
          git config --global user.name "github-action@users.noreply.github.com"
          git add ${package}.rb
          git commit -m "Add bottle DSL"
          git push
          echo ::set-output name=file_name::${file_name}
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.release.outputs.upload_url}}
          asset_path: ${{steps.build.outputs.file_name}}
          asset_name: ${{steps.build.outputs.file_name}}
          asset_content_type: application/tar+gzip
