name: Build and publish bottles

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: skx/github-action-build@master
        with:
          builder: .github/build.sh
      - name: Upload
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.bottle.tar.gz'
