name: Build and publish bottles

on:
  push:
    tags:
      - '*-*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: brew tap ncihnegn/homebrew-formulae
      - name: Build
        id: build
        run: |
          package=$(echo ${{ github.ref }} | cut -d'-' -f1)
          version=$(echo ${{ github.ref }} | cut -d'-' -f2)
          brew install --build-bottle ${package} && brew bottle ${package}
          echo ::set-output name=file_name::${package}--${version}.catalina.bottle.tar.gz
      - name: Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.file_name}}
          asset_name: ${{ steps.build.outputs.file_name}}
          asset_content_type: application/tar+gzip
