name: Build and publish bottles

on:
  create:
    tags:
      - '*-*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{github.ref}}
          draft: false
          prerelease: false
      - name: Prepare
        run: |
          tag=$(echo ${{github.ref}} | cut -c11-)
          package=$(echo $tag | cut -d'-' -f1)
          brew tap ${{github.repository}} && brew update && brew install $(brew deps ${{github.repository}}/${package}) && brew upgrade $(brew deps ${{github.repository}}/${package}
      - name: Build
        id: build
        run: |
          tag=$(echo ${{github.ref}} | cut -c11-)
          package=$(echo $tag | cut -d'-' -f1)
          brew install --build-bottle ${{github.repository}}/${package}
          bottle=$(brew bottle ${{github.repository}}/${package} --root-url https://github.com/${{github.repository}}/releases/download/${tag})
          dash_file_name=$(echo ${bottle} | sed 's/.* \([0-9a-z.-]*.tar.gz\).*/\1/')
          file_name=${dash_file_name/--/-}
          mv ${dash_file_name} ${file_name}
          dsl=$(echo ${bottle} | sed 's/.*\(bottle do.*end\)/\1/')
          echo ${dsl}
          dsl=$(echo ${dsl} | sed -e 's/"/\\"/g' -e 's#/#\\/#g')
          echo ${dsl}
          echo ::set-output name=file_name::${file_name}
          echo ::set-output name=dsl::${dsl}
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.release.outputs.upload_url}}
          asset_path: ${{steps.build.outputs.file_name}}
          asset_name: ${{steps.build.outputs.file_name}}
          asset_content_type: application/tar+gzip
      - name: Commit
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-action@users.noreply.github.com"
          dsl="${{steps.build.outputs.dsl}}"
          package=$(echo ${{github.ref}} | cut -c11- | cut -d'-' -f1)
          perl -0777p -e "s/bottle do.*?end/${dsl}/mgs" -i ${package}.rb
          sed -i.bak -e 's/root_url/\'$'\n    &/' -e 's/cellar/\'$'\n    &/' -e 's/rebuild/\'$'\n    &/' -e 's/\(sha256.*\)/\'$'\n    &/' -e 's/catalina end/catalina\'$'\n  end/' ${package}.rb
          git add ${package}.rb
          git commit -m "Add ${tag} bottle DSL"
          git push
