name: Build and publish bottles

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Prepare
        run: brew upgrade && brew tap ncihnegn/homebrew-formulae
      - name: Build
        run: brew install --build-bottle toml11 && brew bottle toml11
      - name: Upload
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.bottle.tar.gz'
