name: Build and publish bottles

on:
  create:
    tags:
      - '*-*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: brew tap ncihnegn/homebrew-formulae
      - name: Build
        id: build
        run: |
          tag=$(echo ${{github.ref}} | cut -c11-)
          package=$(echo ${tag} | cut -d'-' -f1)
          version=$(echo ${tag} | cut -d'-' -f2)
          brew install --build-bottle ${package}
          bottle=$(brew bottle ${package})
          echo ${bottle}
          checksum=$(echo ${bottle}| grep sha256)
          rebuild=$(echo ${bottle}| grep "rebuild ")
          [ $rebuild != "" ] && rebuildid=$(echo ${rebuild} | cut -c12-)
          sed -i.bak "s/.*sha256.*/${checksum}${rebuild}/" ${package}.rb
          git config --global user.name "GitHub Action"
          git config --global user.name "github-action@users.noreply.github.com"
          git add ${package}.rb
          git commit -m "Add checksum"
          git push
          [ $rebuildid != "" ] && rebuilid+="."
          echo ::set-output name=file_name::${package}--${version}.catalina.bottle${rebuildid}.tar.gz
      - name: Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{github.ref}}
          draft: false
          prerelease: false
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.release.outputs.upload_url}}
          asset_path: ${{steps.build.outputs.file_name}}
          asset_name: ${{steps.build.outputs.file_name}}
          asset_content_type: application/tar+gzip
