name: Build and publish bottles

on:
  create:
    tags:
      - '*-*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: brew tap ncihnegn/homebrew-formulae
      - name: Build
        id: build
        run: |
          package=$(echo ${{github.ref}} | cut -c11- | cut -d'-' -f1)
          brew install --build-bottle ${package}
          bottle=$(brew bottle ${package})
          file_name=$(echo ${bottle} | sed -e 's/\(.*.tar.gz\)/\1/')
          dsl=$(echo ${bottle} | sed -e 's/bottles-formulae.\(.*\)end/\1/')
          sed -i.bak "s/.*sha256.*/${dsl}/" ${package}.rb
          git config --global user.name "GitHub Action"
          git config --global user.name "github-action@users.noreply.github.com"
          git add ${package}.rb
          git commit -m "Add bottle DSL"
          git push
          echo ::set-output name=file_name::${file_name}
      - name: Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{github.ref}}
          draft: false
          prerelease: false
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.release.outputs.upload_url}}
          asset_path: ${{steps.build.outputs.file_name}}
          asset_name: ${{steps.build.outputs.file_name}}
          asset_content_type: application/tar+gzip
