name: Build and publish bottles

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: brew upgrade && brew tap ncihnegn/homebrew-formulae
      - name: Build
        run: brew install --build-bottle toml11 && brew bottle toml11
      - name: Upload
        uses: actions/upload-artifact@v2-preview
        with:
          path: *.bottle.tar.gz
          name: bottles
